lexik_translation_list:
    path:     /translations
    defaults: { _controller: "lexik_translation.controller.rest_controller:listAction" }
    methods:  [GET]

lexik_translation_profiler:
    path:     /translations/profiler/{token}
    defaults: { _controller: "lexik_translation.controller.rest_controller:listByProfileAction" }
    methods:  [GET]

lexik_translation_update:
    path:     /translations/{id}
    defaults: { _controller: "lexik_translation.controller.rest_controller:updateAction" }
    methods:  [PUT]

lexik_translation_delete_locale:
    path:     /translations/{id}/{locale}
    defaults: { _controller: "lexik_translation.controller.rest_controller:deleteTranslationAction" }
    methods:  [DELETE]

lexik_translation_delete:
    path:     /translations/{id}
    defaults: { _controller: "lexik_translation.controller.rest_controller:deleteAction" }
    methods:  [DELETE]
